### ISSUE TITLE
Something funny in the 3-qubit "Realistic Example"

### ISSUE THREAD

**Issue by gnperdue** [Lopez-Santi/QEC_code#24]
In #23 I found the following plot for the "realistic noise" example near the bottom -- should these plots really be the same? @Lopez-Santi 

![Screen Shot 2023-08-09 at 4 55 11 PM](https://github.com/Lopez-Santi/QEC_code/assets/1294053/32d0cd64-d93b-46cb-abed-9d20b521e38c)

**Comment by Lopez-Santi** [comment]
I think the plots are correct. If you look at the states that we have a probability to measure, we can see that they change. (i.e. instead of 01111 we get 11111) This means that it was corrected. The probability of being in 11100 doesn't change because there is no need to apply a correction. But others may and will change since a correction is applied.

**Comment by gnperdue** [comment]
Okay, thanks, I missed that the labels on the x-axis changed. But yes, I see the corrected states are all in the code space, while for the uncorrected, they aren't.
